name: Secret Expiry Alert

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} # Set the GH_TOKEN environment variable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List repository secrets
        id: list_secrets
        run: |
          gh api repos/${{ github.repository }}/actions/secrets --paginate > secrets.json
          echo "::set-output name=secrets::$(jq -r '.secrets[] | @base64' secrets.json)"

      - name: Check and print expiring or expired secrets
        run: |
          secrets=${{ steps.list_secrets.outputs.secrets }}
          for secret in $secrets; do
            decoded_secret=$(echo $secret | base64 --decode)
            name=$(echo $decoded_secret | jq -r '.name')
            echo "secret name : $name"
            created_at=$(echo $decoded_secret | jq -r '.created_at')
            expiry_date=$(date -d "$created_at + 30 days" +%Y-%m-%d) # Assuming secrets expire after 90 days
            today=$(date +%Y-%m-%d)
            if [[ "$expiry_date" < "$today" || "$expiry_date" == "$today" ]]; then
              echo "Secret $name has expired or is expiring today (Expiry Date: $expiry_date)."
            fi
          done
